### ISSUE TITLE
Unable to get Environment setup on Windows

### ISSUE THREAD

**Issue by Landelor** [andrewminer/crafting-guide#259]
Hi,

I'm running through the steps in the Wiki, but am unable to get it going. I get the following when I run `grunt clean start`

```
$ grunt clean start
Running "clean:assets" (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "clean:dist" (clean) task
>> 1 path cleaned.

Running "clean:templates" (clean) task
>> 0 paths cleaned.

Running "script:start" task
Fatal error: spawn .\scripts\start ENOENT
```

Adding -x to the start script brings up this.

```
+ nodemon ./server.coffee
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./server.coffee ./dist/index.js`
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Crafting-Guide\crafting-guide\server.coffee'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
[nodemon] app crashed - waiting for file changes before starting...
Running "watch" task
Waiting...

```

Any help would be appreciated.

**Comment by andrewminer** [comment]
Looks like you need to run `grunt clean build start`.  I'll update the docs.

**Comment by andrewminer** [comment]
Fixed.

**Comment by Landelor** [comment]
Still no go. Not getting this to run on any OS install.

Linux (Ubuntu):

```
./scripts/start: line 7: nodemon: command not found


Done, without errors.
landelor@CraftingGuide:~crafting-guide$ Running "watch" task
Waiting...
```

It says waiting but nothing is loading in a browser.

Windows:

```
$ grunt clean build start
Running "clean:assets" (clean) task
>> 1 path cleaned.

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "clean:templates" (clean) task
>> 1 path cleaned.

Running "jade:pages" (jade) task
>> 1 file created.

Running "jade:templates" (jade) task
>> 1 file created.

Running "copy:assets_build" (copy) task
Created 2 directories, copied 25 files

Running "copy:env_build" (copy) task


Running "copy:common_source" (copy) task
Copied 4 files

Running "copy:server_source" (copy) task
Copied 4 files

Running "sass_globbing:all" (sass_globbing) task

Running "sass:all" (sass) task

Running "browserify:external" task

Running "browserify:internal" task

Running "script:start" task
Fatal error: spawn .\scripts\start ENOENT
```

With -x

```
+ nodemon ./server.coffee
./scripts/start: line 7: nodemon: command not found
+ echo ''

+ popd

Landelor@VARIAN MINGW64 /d/CraftingGuide/crafting-guide (master)
$ Running "watch" task
Waiting...
```

Again nothing loading in a browser.

Regards,
